/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.opciones;

import Logica.GuardadoAutomatico;
import Logica.LeerEscribirObjetos;
import gui.PantallaPrincipal;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alvar
 */
public class PantallaOpciones extends javax.swing.JDialog {

    //variable para escribir/leer objetos
    LeerEscribirObjetos leo = new LeerEscribirObjetos();

    /**
     * Creates new form PantallaOpciones
     */
    public PantallaOpciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //iniciamos el looka and fell
        DefaultComboBoxModel dcb = new DefaultComboBoxModel();
        for (UIManager.LookAndFeelInfo l : UIManager.getInstalledLookAndFeels()) {
            dcb.addElement(l.getName());
        }
        jComboBoxLookAndFeel.setModel(dcb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxLookAndFeel = new javax.swing.JComboBox<>();
        jButtonCargar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jSliderGuardadoAutomático = new javax.swing.JSlider();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        jComboBoxLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLookAndFeelActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLookAndFeel);

        jButtonCargar.setText("Cargar");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCargar);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar);

        jSliderGuardadoAutomático.setMaximum(20);
        jSliderGuardadoAutomático.setMinimum(1);
        jSliderGuardadoAutomático.setToolTipText("");
        jSliderGuardadoAutomático.setValue(10);
        jSliderGuardadoAutomático.setBorder(javax.swing.BorderFactory.createTitledBorder("Guardado Automático"));
        jPanel1.add(jSliderGuardadoAutomático);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:

        LeerEscribirObjetos leo = new LeerEscribirObjetos();
        try {
            leo.guardar();
            JOptionPane.showMessageDialog(this, "Guardado", "Correcto", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        // TODO add your handling code here:
        LeerEscribirObjetos leo = new LeerEscribirObjetos();
        try {
            leo.cargar();
            JOptionPane.showMessageDialog(this, "Datos cargados", "Cargar", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(PantallaOpciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaOpciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        //Sacamos el valor del deslizador
        int i=jSliderGuardadoAutomático.getValue();
        GuardadoAutomatico.cambiarTiempo(i);
        System.out.println(i);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jComboBoxLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLookAndFeelActionPerformed
        // TODO add your handling code here:
        //recogo la posicion sleccionada
        int seleccionado = jComboBoxLookAndFeel.getSelectedIndex();
        //Cargo el lookAndFell
        LookAndFeelInfo lafi = UIManager.getInstalledLookAndFeels()[seleccionado];
        Logica.LookAndFeel.cambiarLookAndFeel(lafi.getClassName());
        Logica.LookAndFeel.actulizarLookAndFeel(this);
    }//GEN-LAST:event_jComboBoxLookAndFeelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxLookAndFeel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderGuardadoAutomático;
    // End of variables declaration//GEN-END:variables
}
