/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.carreras;

import dto.Carrera;
import gui.TableModels.CorredoresTableModels;
import java.awt.Frame;
import java.util.ArrayList;
import dto.Corredor;
import java.util.AbstractList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author alvar
 */
public class PantallaCarrerasInscribirCorredor extends javax.swing.JDialog {

    private Carrera carrera;
    public  List<Corredor> corredoresInscritos;
    public  List<Corredor> corredoresNOInscritos;
    
    /**
     * Creates new form PantallaCarrerasInscribirCorredor
     */
    
    public PantallaCarrerasInscribirCorredor(java.awt.Frame parent, boolean modal, Carrera c) {
        super(parent, modal);
        carrera=c;      
        corredoresInscritos=new ArrayList<>();
        corredoresNOInscritos=new ArrayList<>();
        initComponents();
        this.cargarInscritosYNo();
        //jTableCorredoresInscritos.setModel(new CorredoresTableModels(this.corredoresInscritos));
        jTableNoInscritos.setModel(new CorredoresTableModels(Logica.LogicaCorredores.getListaCorredores()));
        jTableCorredoresInscritos.setModel(new CorredoresTableModels(corredoresInscritos));
        //jTableCorredoresInscritos.setModel(new CorredoresTableModels(corredoresNOInscritos));
        
        
    }

    
    //Metodo para cargar los corredores inscritos
    private void cargarInscritosYNo(){
        
        //En no inscrituos cargamos a todos
        corredoresNOInscritos=Logica.LogicaCorredores.getListaCorredores();
        Corredor a=new Corredor("aa", "aa", "15/12/1994", "ee", 5);
        corredoresNOInscritos.add(a);
        corredoresInscritos.add(a);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNoInscritos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCorredoresInscritos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableNoInscritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNoInscritos);

        jLabel1.setText("Bolsa de Corredores");

        jTableCorredoresInscritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCorredoresInscritos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCorredoresInscritos;
    private javax.swing.JTable jTableNoInscritos;
    // End of variables declaration//GEN-END:variables
}
