/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.carreras;

import dto.Carrera;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.PieChart;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alvar
 */
public class PantallaCarraresLlegadaCorredor extends javax.swing.JDialog {

    /**
     * Creates new form PantallaCarraresLlegadaCorredor
     */
    private List<Integer> dorsales = new ArrayList<>();
    private String tiempo;
    private Carrera carrera;

    public PantallaCarraresLlegadaCorredor(java.awt.Frame parent, boolean modal, List<Integer> d, String t, Carrera c) {
        super(parent, modal);
        initComponents();
        this.dorsales = d;
        this.tiempo = t;
        this.carrera = c;
        //Cargo el combo box      
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for (int i : dorsales) {
            dcbm.addElement(i);
        }
        jComboBoxDorsales.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDorsales = new javax.swing.JComboBox<>();
        jButtonMeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxDorsales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonMeta.setText("Meta");
        jButtonMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMeta)
                    .addComponent(jComboBoxDorsales, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jComboBoxDorsales, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButtonMeta)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetaActionPerformed
        // TODO add your handling code here:
        Logica.LogicaCarrera.corredorLlega(carrera, (int) jComboBoxDorsales.getSelectedItem(), tiempo);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonMetaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMeta;
    private javax.swing.JComboBox<String> jComboBoxDorsales;
    // End of variables declaration//GEN-END:variables
}
